/* Generated by            cobc 1.1.0 */
/* Generated from          hello.cob */
/* Generated at            Mar 09 2022 22:44:04 EST */
/* OpenCOBOL build date    Mar 09 2022 22:21:43 */
/* OpenCOBOL package date  Feb 06 2009 10:30:55 CET */
/* Compile command         cobc -free -C hello.cob */


/* Define perform frame stack */

struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];

