;
; File generated by cc65 v 2.13.3
;
	.fopt		compiler,"cc65 v 2.13.3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

L0001:
	.byte	$D3,$54,$41,$52,$54,$2E,$2E,$2E,$0D,$00,$C4,$4F,$4E,$45,$0D,$00
	.byte	$53,$55,$4D,$20,$3D,$20,$25,$44,$0D,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$00
	jsr     pusheax
	jsr     decsp2
	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0006:	ldy     #$01
	jsr     ldaxysp
	cmp     #$10
	txa
	sbc     #$27
	bvc     L000D
	eor     #$80
L000D:	asl     a
	lda     #$00
	ldx     #$00
	rol     a
	jne     L0009
	jmp     L0007
L0009:	ldy     #$01
	jsr     ldaxysp
	jsr     axlong
	ldy     #$02
	jsr     laddeqysp
	ldy     #$01
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	jsr     incax1
	ldy     #$00
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jmp     L0006
L0007:	lda     #<(L0001+10)
	ldx     #>(L0001+10)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	lda     #<(L0001+16)
	ldx     #>(L0001+16)
	jsr     pushax
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	jsr     _printf
	jsr     incsp6
	rts

.endproc

